import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/organisms/navbar/Navbar'
import Mainpage from './MainPage/Mainpage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Design 1 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={"lg:px-[200px] lg:h-screen lg:w-full "}>
        <Navbar />
        <Mainpage />
      </section>

      </>
  )
}
